openapi: 3.1.0
info:
    title: Baseball Stats
    description: Get current and historical statistics for MLB players, teams, games, and seasons.
    version: "v1"
servers:
    - url: http://localhost:5003
paths:
    /standings:
        get:
            operationId: getStandings
            summary: Retrieves the overall standings for all teams across the MLB depending on the year that is supplied.
            description: The operation will retrieve the ranking of every team within their respective division across Major League Baseball (MLB). 
            parameters:
                - in: query
                  name: year
                  required: true
                  schema:
                    type: integer
                  description: Used to filter the year the overall standings should be returned for.
            responses:
                "200":
                    description: Returns the overall league standings.
                    content:
                      application/json:
                        schema: 
                            type: array

    /news:
        get:
            operationId: getNews
            summary: Retrieves up to date news articles for teams from mlb.com. 
            parameters:
              - in: query
                name: team_name
                required: true
                schema:
                  type: string
                description: Used to filter out relevant news articles for the team being specified.
            responses:
              "200":
                description: OK
                content:
                  application/json:
                    schemas:
                      type: array
    
    /batting_stats_bref:
      get:
          operationId: getBattingStatsBaseballReference
          summary: Retrieves all batting statistics from Baseball Reference for the season being inputted. 
          parameters:
            - in: query
              name: year
              required: true
              schema:
                type: integer
              description: Used to filter batting statistics based on the year being specified.
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
    
    /pitching_stats_bref:
      get:
          operationId: getPitchingStatsBaseballReference
          summary: Retrieves all pitching statistics from Baseball Reference for the season being inputted.
          parameters:
            - in: query
              name: year
              required: true
              schema: 
                type: integer
              description: Used to select which season the pitching statistics will be retrieved from. 
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
    
    /team_batting:
      get:
          operationId: getTeamBatting
          summary: Retrieves the batting statistics for all players on a team for the season being inputted.
          parameters:
            - in: query
              name: team_abbreviation
              required: true
              schema:
                type: string
              description: The 3 letter abbreviated name of the baseball team.
              example: NYY
            - in: query
              name: year
              required: true
              schema: 
                type: integer
              description: Used to select which season the team batting statistics will be retrieved from.
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema: 
                    type: object

    /team_fielding:
      get: 
          operationId: getTeamFielding
          summary: Retrieves all the teams combined fielding statistics for the provided season
          parameters:
            - in: query
              name: year
              required: true
              schema: 
                type: integer
              description: Used to select which season the team fielding statistics will be retrieved from. 
          responses: 
            "200":
              description: A complex JSON object response
              content:
                application/json:
                  schema: 
                    type: object

    /team_pitching:
      get: 
        operationId: getTeamPitching
        summary: Retrieves all the teams combined pitching statistics for the provided season
        parameters:
          - in: query
            name: year
            required: true
            description: Used to select which season the team fielding statistics will be retrieved from
            schema: 
              type: integer
        responses:
          "200":
            description: A complex JSON object response
            content:
              application/json:
                schema: 
                  type: object

    /statcast_playerid_lookup:
        get:
            operationId: getPlayerIdLookup
            summary: Retrieves a player ID value to be used with other statcast data retrieval functions. 
            parameters:
              - in: query
                name: first
                required: true
                description: A player's first name.
                schema: 
                  type: string 
              - in: query
                name: last
                required: true
                description: A player's last name.
                schema: 
                  type: string
            responses:
              "200":
                description: >
                  A player ID should be returned. This ID can be used to retrieve other statistics from statcast functions. 
                  This ID will not be useful for a user. The model should use this for querying individual player statistics.
              "500":
                description: Error. Multiple players and their IDs are returned. Display the results in a markdown table. 

    /statcast_batter:
        get:
            operationId: getStatcastBatter
            summary: Retrieves pitch-level statistics for a batter for a given date. 
            parameters:
              - in: query
                name: date
                required: true
                description: The date that data should be retrieved from. 
                schema:
                  type: string
                  format: date
                  description: The date in the format of 'YYYY-MM-DD'.
              - in: query
                name: key_mlbam
                required: true
                description: >
                  The MLBAM player ID of the player you want to retrieve data for. This value can be retrieved by invoking 
                  the operation with operationId 'getPlayerIdLookup'.
                schema: 
                  type: integer
            responses:
              "200":
                description: A complex JSON object response
                content:
                  application/json:
                    schema:
                      type: object
              "500":
                description: Error. Starting date is before the year 2008. This is before statcast data starting being collected. 
    
    /statcast_fielding:
        get: 
          operationId: getStatcastFielding
          summary: Retrieves fielding statstics of a position over a season time frame.
          parameters:
            - in: query
              name: position_abbreviation
              required: true
              description: The two letter position abbreviation
              schema:
                type: string
              example: SS
            - in: query
              name: year
              required: true
              description: The year that fielding statistics should be retrieved from.
              schema: 
                type: integer
          responses:
            "200":
              description: A complext JSON object response 
              content:
                application/json:
                  schema: 
                    type: object
            "500": 
              description: Error. Statcast data can't be retrieved for years before 2008. 

    /statcast_pitcher:
        get: 
          operationId: getStatcastPitcher
          summary: Retrieves pitch-level statistics for a pitcher for a specified date.
          parameters:
              - in: query
                name: start_date
                required: false
                description: The date from which data will be retrieved. 
                schema:
                  type: string
                  format: date
                  description: The date in the format of 'YYYY-MM-DD'.
              - in: query
                name: key_mlbam
                required: true
                description: >
                  The MLBAM player ID of the player you want to retrieve data for. This value can be retrieved by invoking 
                  the operation with operationId 'getPlayerIdLookup'.
                schema: 
                  type: integer
          responses:
              "200":
                description: A complex JSON object response
                content:
                  application/json:
                    schema:
                      type: object
              "500":
                description: Error. Starting date is before the year 2008. This is before statcast data starting being collected.  
            
                
