openapi: 3.1.0
info:
    title: Baseball Stats
    description: Get current and historical statistics for MLB players, teams, games, and seasons.
    version: "v1"
servers:
    - url: http://localhost:5003
paths:
    /standings:
        get:
            operationId: getStandings
            summary: Retrieves the overall standings for all teams across the MLB depending on the year that is supplied.
            description: The operation will retrieve the ranking of every team within their respective division across Major League Baseball (MLB). 
            parameters:
                - in: query
                  name: year
                  required: true
                  schema:
                    type: integer
                  description: Used to filter the year the overall standings should be returned for.
            responses:
                "200":
                    description: Returns the overall league standings.
                    content:
                      application/json:
                        schema: 
                            $ref: '#/components/schemas/getStandingsResponse'

    /news:
        get:
            operationId: getNews
            summary: Retrieves up to date news articles for teams from mlb.com. 
            parameters:
              - in: query
                name: team_name
                required: true
                schema:
                  type: string
                description: Used to filter out relevant news articles for the team being specified.
            responses:
              "200":
                description: OK
                content:
                  application/json:
                    schemas:
                      type: array
    
    /batting_stats_fangraphs:
      get:
          operationId: getBattingStatsFangraphs
          summary: Retrieves all batting statistics from FanGraphs for the season being inputted. 
          parameters:
            - in: query
              name: year
              required: true
              schema:
                type: integer
              description: Used to filter batting statistics based on the year being specified.
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
    
    /pitching_stats_fangraphs:
      get:
          operationId: getPitchingStatsFangraphs
          summary: Retrieves all pitching statistics from FanGraphs for the season being inputted.
          parameters:
            - in: query
              name: year
              required: true
              schema: 
                type: integer
              description: Used to select which season the pitching statistics will be retrieved from. 
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
    
    /team_batting:
      get:
          operationId: getTeamBatting
          summary: Retrieves all teams' combined batting statistics for the season being inputted.
          parameters:
            - in: query
              name: year
              required: true
              schema: 
                type: integer
              description: Used to select which season the team batting statistics will be retrieved from.
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema: 
                    type: object

    /team_fielding:
      get: 
          operationId: getTeamFielding
          summary: Retrieves all the teams combined fielding statistics for the provided season
          parameters:
            - in: query
              name: year
              required: true
              schema: 
                type: integer
              description: Used to select which season the team fielding statistics will be retrieved from. 
          responses: 
            "200":
              description: A complex JSON object response
              content:
                application/json:
                  schema: 
                    type: object

    /team_pitching:
      get: 
        operationId: getTeamPitching
        summary: Retrieves all the teams combined pitching statistics for the provided season
        parameters:
          - in: query
            name: year
            required: true
            description: Used to select which season the team fielding statistics will be retrieved from
            schema: 
              type: integer
        responses:
          "200":
            description: A complex JSON object response
            content:
              application/json:
                schema: 
                  type: object

    /statcast_playerid_lookup:
        get:
            operationId: getPlayerIdLookup
            summary: Retrieves a player ID value to be used with other statcast data retrieval functions. 
            parameters:
              - in: query
                name: first
                required: true
                description: A player's first name.
                schema: 
                  type: string 
              - in: query
                name: last
                required: true
                description: A player's last name.
                schema: 
                  type: string
            responses:
              "200":
                description: >
                  A player ID should be returned. This ID can be used to retrieve other statistics from statcast functions. 
                  This ID will not be useful for a user. The model should use this for querying individual player statistics.
              "500":
                description: Error. Multiple players and their IDs are returned. Display the results in a markdown table. 

    /statcast_batter:
        get:
            operationId: getStatcastBatter
            summary: Retrieves pitch-level statistics for a batter over a given time period. 
            parameters:
              - in: query
                name: start_date
                required: false
                description: The starting date from which data will be retrieved from. If no value is given, the function will use yesterday's date by default. 
                schema:
                  type: string
                  format: date
                  description: The date in the format of 'YYYY-MM-DD'.
              - in: query
                name: ending_date
                required: false
                description: The last day from which you want to retrieve data. If no value is provided, the function will use the current day by default. 
                schema: 
                  type: string
                  format: date
                  description: The date in the format of 'YYYY-MM-DD'. 
              - in: query
                name: key_mlbam
                required: true
                description: >
                  The MLBAM player ID of the player you want to retrieve data for. This value can be retrieved by invoking 
                  the operation with operationId 'getPlayerIdLookup'.
                schema: 
                  type: integer
            responses:
              "200":
                description: A complex JSON object response
                content:
                  application/json:
                    schema:
                      type: object
              "500":
                description: Error. Starting date is before the year 2008. This is before statcast data starting being collected. 
    
    /statcast_fielding:
        get: 
          operationId: getStatcastFielding
          summary: Retrieves fielding statstics for all players across the MLB for a given year.
          parameters:
            - in: query
              name: year
              required: true
              description: The year that fielding statistics should be retrieved from.
              schema: 
                type: integer
          responses:
            "200":
              description: A complext JSON object response 
              content:
                application/json:
                  schema: 
                    type: object
            "500": 
              description: Error. Statcast data can't be retrieved for years before 2008. 

    
            


                
    /players:
        get:
            operationId: getPlayers
            summary: Retrieves all players from all seasons whose names match the query string.
            parameters:
                - in: query
                  name: query
                  schema:
                      type: string
                  description: Used to filter players based on their name. For example, ?query=davis will return players that have 'davis' in their first or last name.
            responses:
                "200":
                    description: OK
    /teams:
        get:
            operationId: getTeams
            summary: Retrieves all teams for the current season.
            responses:
                "200":
                    description: OK
    /games:
        get:
            operationId: getGames
            summary: Retrieves all games that match the filters specified by the args. Display results using markdown tables.
            parameters:
                - in: query
                  name: limit
                  schema:
                      type: string
                  description: The max number of results to return.
                - in: query
                  name: seasons
                  schema:
                      type: array
                      items:
                          type: string
                  description: Filter by seasons. Seasons are represented by the year they began. For example, 2018 represents season 2018-2019.
                - in: query
                  name: team_ids
                  schema:
                      type: array
                      items:
                          type: string
                  description: Filter by team ids. Team ids can be determined using the getTeams function.
                - in: query
                  name: start_date
                  schema:
                      type: string
                  description: A single date in 'YYYY-MM-DD' format. This is used to select games that occur on or after this date.
                - in: query
                  name: end_date
                  schema:
                      type: string
                  description: A single date in 'YYYY-MM-DD' format. This is used to select games that occur on or before this date.
            responses:
                "200":
                    description: OK
    /stats:
        get:
            operationId: getStats
            summary: Retrieves stats that match the filters specified by the args. Display results using markdown tables.
            parameters:
                - in: query
                  name: limit
                  schema:
                      type: string
                  description: The max number of results to return.
                - in: query
                  name: player_ids
                  schema:
                      type: array
                      items:
                          type: string
                  description: Filter by player ids. Player ids can be determined using the getPlayers function.
                - in: query
                  name: game_ids
                  schema:
                      type: array
                      items:
                          type: string
                  description: Filter by game ids. Game ids can be determined using the getGames function.
                - in: query
                  name: start_date
                  schema:
                      type: string
                  description: A single date in 'YYYY-MM-DD' format. This is used to select games that occur on or after this date.
                - in: query
                  name: end_date
                  schema:
                      type: string
                  description: A single date in 'YYYY-MM-DD' format. This is used to select games that occur on or before this date.
            responses:
                "200":
                    description: OK
    /season_averages:
        get:
            operationId: getSeasonAverages
            summary: Retrieves regular season averages for the given players. Display results using markdown tables.
            parameters:
                - in: query
                  name: season
                  schema:
                      type: string
                  description: Defaults to the current season. A season is represented by the year it began. For example, 2018 represents season 2018-2019.
                - in: query
                  name: player_ids
                  schema:
                      type: array
                      items:
                          type: string
                  description: Filter by player ids. Player ids can be determined using the getPlayers function.
            responses:
                "200":
                    description: OK

components:
  schemas:
    getStandingsResponse:
        type: object
        properties:
            overall_standings:
                type: array
                items:
                - name: index
                  type: integer
                  description: The team's ranking in the division.
                - name: Tm
                  type: string
                  description: The team's name.
                - name: W
                  type: string
                  description: The number of wins the team has.
                - name: L
                  type: string
                  description: The number of losses the team has.
                - name: W-L%
                  type: string
                  description: The team's win to loss ratio.
                - name: GB
                  type: string
                  description: The number of games the team is behind first place.

                
